name: MoreLoreEffectsPlugin
version: '1.12.2-a0.3.0'
main: org.clinlx.moreloreeffectsplugins.MoreLoreEffectsPlugin
description: 通过修改物品的Lore，加入特殊的词条，可以给任意物品添加一些额外属性。
authors: [ Clinlx,Kurumi ]
commands:
  lorelist:
    #别名
    aliases: lls
    #描述这个命令
    description: "查询现版本服务器中可用的所有特殊Lore词条. 别名:/lls"
    #用法
    usage: "/lorelist [选项]  §7§l查询服务器中所有特殊Lore词条
    注：选项可为{all,uni,atk,dfn}，若无参数则显示全部可用词条Lore"
    #没有权限的提示消息
    permission-message: "无权使用"
  loreskills:
    #别名
    aliases: llsk
    #描述这个命令
    description: "查询当前服务器数据中所有已经设置的Lore技能. 别名:/llsk"
    #用法
    usage: "/loreskills"
    #没有权限的提示消息
    permission-message: "无权使用"
  setloreskill:
    #别名
    aliases: slsk
    #描述这个命令
    description: "在服务器数据中添加或修改一项Lore技能. 别名:/slsk"
    #用法
    usage: "/setloreskill [技能名] [冷却] [效果]  §7§l在服务器数据中注册一项Lore技能
    注：冷却为整数，单位：毫秒。;
    效果项是一条要执行的指令，由服务器执行，不用输入‘/’号，指令中用@s来指代物品使用者;
    效果项中的&符号将会被转义为颜色符号，&&连用会被转义为单个&符号"
    #没有权限的提示消息
    permission-message: "无权使用"
  delloreskill:
    #别名
    aliases: dlsk
    #描述这个命令
    description: "删除一项已经在服务器数据中设置的Lore技能. 别名:/dlsk"
    #用法
    usage: "/delloreskill [技能名]  §7§l在服务器数据中去除一项Lore技能"
    #没有权限的提示消息
    permission-message: "无权使用"
  loadskillcode:
    #别名
    aliases: lskc
    #描述这个命令
    description: "指定一个Lore技能效果使用的lua代码文件，会替换技能原本的属性设置. 别名:/lskc"
    #用法
    usage: "/loadskillcode [技能名] [文件名] §7§l指定一个Lore技能效果使用的lua代码文件，文件目录：loreskillcodes/"
    #没有权限的提示消息
    permission-message: "无权使用"